/* Test functionality from ch. 1.6 exception handling
 * Janus Bo Andersen, Sep 2019
 * */

#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}